---
# tasks file for ruby(On Debian family)
- name: Install requirements for building Ruby extention modules
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 install_recommends=no
  with_items:
    - build-essential
    - ruby-dev
  become: yes
- name: Install Ruby with APT
  apt: name=ruby update_cache=yes cache_valid_time=3600 install_recommends=no
  become: yes
